In [4]:
import numpy as np

In [6]:
np.zeros(4) # one dimentions 

array([0., 0., 0., 0.])

### All ones 

In [11]:
np.ones((4,5,4), dtype = 'int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

### All Other numbers 

In [14]:
np.full((2,3),99) ## 2*3 array with all 99

array([[99, 99, 99],
       [99, 99, 99]])

In [16]:
a = [[1,2],[3,43]]
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

### Array with random numbers

In [19]:
np.random.rand(4,5)

array([[0.25606081, 0.88541714, 0.47664936, 0.65926004, 0.58107429],
       [0.92879643, 0.43666618, 0.27317944, 0.68941728, 0.33883569],
       [0.58656299, 0.54360262, 0.36335888, 0.09483961, 0.92576173],
       [0.62525881, 0.51245877, 0.66617142, 0.35954814, 0.76054783]])