In [11]:
import numpy as np 

# Arrays  Basics

### Defining an array

In [14]:
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


### Multidimensional Array 

In [4]:
b = np.array([[4,5,6,23,21],[23,34,54,67,89]])
print(b)

[[ 4  5  6 23 21]
 [23 34 54 67 89]]


### Get the dimension of the array 


In [9]:
a.ndim

1

In [8]:
b.ndim

2

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 5)

## Get the type of the variable 

In [15]:
a.dtype

dtype('int16')

In [13]:
b.dtype

dtype('int64')

## Get the size of the variable

In [16]:
a.itemsize 

2

In [17]:
b.itemsize

8

In [18]:
# Total size 
a.nbytes

6

## Accessing/ Changing specific elements rows columns , etc

In [21]:
c= np.array([[1,5,3,47,67,54,56],[45,45,67,645,32,34,64]])
print(c)

[[  1   5   3  47  67  54  56]
 [ 45  45  67 645  32  34  64]]


In [22]:
# Gettting an elemtent from the array 
c[1,4]

32

### Getting the entire row/column from an array 

In [23]:
c[0, :]

array([ 1,  5,  3, 47, 67, 54, 56])

In [26]:
c[ : , 2]

array([ 3, 67])

### Getting group of elemnents 

In [27]:
# First two are indexes and the third one is the step size 
c[0, 1:6:2]

array([ 5, 47, 54])

### Changing Elements 

In [28]:
c[1,5] = 10
c

array([[  1,   5,   3,  47,  67,  54,  56],
       [ 45,  45,  67, 645,  32,  10,  64]])

In [29]:
c[:,2] = 5
c

array([[  1,   5,   5,  47,  67,  54,  56],
       [ 45,  45,   5, 645,  32,  10,  64]])

## 3 d array 

In [30]:
d = np.array([[[1,2],[4,5]],[[6,5],[45,54]]])
d


array([[[ 1,  2],
        [ 4,  5]],

       [[ 6,  5],
        [45, 54]]])

Getting specific element 

In [31]:
d[0,1,1] 

5

replacing 

In [35]:
d[:,1,:] = [[5,4],[7,45]]
d

array([[[ 1,  2],
        [ 5,  4]],

       [[ 6,  5],
        [ 7, 45]]])

## Zero array 

In [36]:
np.zeros(4)

array([0., 0., 0., 0.])

In [40]:
np.zeros((4,5)) # multidimensional

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## All ones 

In [41]:
np.ones((4,4), dtype="int32")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

### All other numbers 

In [43]:
np.full((3,4),98)

array([[98, 98, 98, 98],
       [98, 98, 98, 98],
       [98, 98, 98, 98]])

## Constant with the size of existing array 

In [12]:
a=np.array([[1,3],[4,5]])
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

### Array with random Decimals 

In [4]:
np.random.rand(4,5)

array([[0.29742574, 0.07174528, 0.12955381, 0.32131754, 0.18013567],
       [0.33366638, 0.55049126, 0.95095479, 0.68914667, 0.11860389],
       [0.74487109, 0.97290399, 0.77632195, 0.68697255, 0.46471742],
       [0.6328616 , 0.94261241, 0.99734448, 0.75431911, 0.59288535]])

In [14]:
np.random.random_sample(a.shape) # with shape of defined array 

array([[0.89369006, 0.08598913],
       [0.92509215, 0.05911556]])

### Array with random Integers

In [17]:
np.random.randint(4,7, size=(3,3)) # with 4 to 7 

array([[6, 5, 4],
       [5, 6, 4],
       [4, 4, 5]])

### Identity Matrix 

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array with repeating predefined array  

In [25]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Example 1

In [36]:
output = np.ones((5,5))
print(output)
z= np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Beware When Copying 

In [40]:
a= np.array([1,3,4])
b=a
b[0]= 100 # This will replace a too 
a 


array([100,   3,   4])

### Copying properly 

In [42]:
a = np.array([34,53,53])
b= np.copy(a)
b[1]=132412
a

array([34, 53, 53])

## Elementwise Additions /substraction ...

In [47]:
a= np.array([1,3,4])
a+2 # adds two to each entries 
a-2 # substracts two from each entries 
a*2 # multiples two to each entries 
a/2 # divides two to each entry of the matrix

array([0.5, 1.5, 2. ])

In [49]:
b= np.array([43,54,45])
a+b # elementwise addition a and b 

array([44, 57, 49])

In [52]:
a ** 2 ## squares a 
a ** 4 ## 4th power of each element in a 

array([  1,  81, 256])

 ### Triganometric funtionms 

In [58]:
np.sin(a)
np.tan(a)

array([ 1.55740772, -0.14254654,  1.15782128])

### Linear Algebra

In [69]:
a = np.full((2,3),2)
b = np.ones((3,2))


#matrix multiplication 
np.matmul(a,b)

#Determinant  
c= np.full((2,2),3)
np.linalg.det(c)

0.0

### Statitics

In [73]:
stats = np.array([[1,2,3],[4,2,4]])
stats

array([[1, 2, 3],
       [4, 2, 4]])

In [83]:
np.min(stats) # minimum 
np.max(stats, axis = 0) #maximum row 
np.max(stats, axis = 1) # maximum column
np.sum(stats, axis=0) # sum along rows

array([5, 4, 7])

### Reorganising Arrays 

In [89]:
before = np.array([[1,2,34,4],[43,54,3,3]])
after = before.reshape((2,2,2))
after

array([[[ 1,  2],
        [34,  4]],

       [[43, 54],
        [ 3,  3]]])

# Vertically stacking vectors 

In [91]:
v1= np.array([1,2,3,4])
v2= np.array([43,45,45,43])
np.vstack([v1,v2,v2,v1])

array([[ 1,  2,  3,  4],
       [43, 45, 45, 43],
       [43, 45, 45, 43],
       [ 1,  2,  3,  4]])

## Horizontal stacks 

In [93]:
h1 = np.ones((2,3))
h2 = np.zeros((2,4))
np.hstack((h1,h2))

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

# Miscallenous

### load from file

In [97]:
filedata = np.genfromtxt('data.txt', delimiter=',') ##gets information from a file as decimals 
filedata.astype(int32) ## Converts fiel into integer 


NameError: name 'int32' is not defined

### Boolean masking  Advanced Indexing 

In [99]:
a> 2

array([[False, False, False],
       [False, False, False]])

In [102]:
a[a >1]

array([2, 2, 2, 2, 2, 2])

In [105]:
a = np.array([1,2,3,4])# index with a list 
a[[0,2,3]]

array([1, 3, 4])

In [110]:
np.any(b>1,axis=1) #along column
np.all(b>1, axis =0)

array([False, False])

In [111]:
(b > 2) & (b<4)

array([[False, False],
       [False, False],
       [False, False]])